{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

COPY systemctl3.py /usr/bin/systemctl

# RUN if [ $(command -v apt-get) ]; then \
#         apt-get update -y && \
#         apt-get install -y apt-utils gcc git python3 python3-dev python3-pip libssl-dev sudo &&\
#         apt-get install -y python2; \
#     elif [ $(command -v yum) ]; then \
#         sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
#         sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* &&\
#         yum install -y python2; \
#     fi

RUN pip install psutil

CMD /usr/bin/systemctl
